#!/usr/bin/env python3
"""Send dhcpd statistics generated by dhcpd-pools to graphite

Does not attempt to reconnect if the server is unavailable.
"""

import argparse
from binascii import hexlify
from collections import namedtuple
import json
from math import trunc
import pathlib
import pickle
import re
import socket
import string
import struct
import subprocess
import sys
from time import time

DEFAULT_PREFIX = "nav"
DEFAULT_CONFIG_FILE = "/etc/dhcpd/dhcpd.conf"
DEFAULT_CMD_PATH = pathlib.Path("/usr/bin/dhcpd-pools")
DEFAULT_PORT = "2004"
DEFAULT_PROTOCOL = 'text'  # MB doesn't trust pickle so we go with text

# graphite likes pickle protocol 2. Python 3: 3, Python 3.8+: 4
PICKLE_PROTOCOL = range(0, pickle.HIGHEST_PROTOCOL + 1)
FLAGS = "-f j"

# maps metric names used by dhcpd-pools to those used in NAV
METRIC_MAPPER = {
    "defined": "total",
    "used": "assigned",
    "touched": "declined",
}


Metric = namedtuple("Metric", ["path", "value", "timestamp"])


# parse comand line flags
def parse_args():
    parser = argparse.ArgumentParser(description="Send dhcp stats to graphite")
    parser.add_argument(
        "address",
        help="Graphite server to send data to",
        type=str,
    )
    parser.add_argument(
        "--port",
        help="Port of Graphite server, if not on 2003 (text) or 2004 (pickle)",
        type=str,
    )
    parser.add_argument(
        "-f",
        "--config-file",
        type=pathlib.Path,
        help="Complete path to dhcpd-pools config-file. Usually located in /etc/dhcpd/. Default: %(default)s",
        default=DEFAULT_CONFIG_FILE,
    )
    parser.add_argument(
        "-C",
        "--command",
        help="Path to dhcpd-pools command. Default: %(default)s",
        type=pathlib.Path,
        default=DEFAULT_CMD_PATH,
    )
    parser.add_argument(
        "-p",
        "--prefix",
        help="Name of first segment to be used in graphite paths. Default: %(default)s",
        type=str,
        default=DEFAULT_PREFIX,
    )
    parser.add_argument(
        "-s",
        "--server-name",
        help="A unique nickname for the dhcpd server, e.g. 'dhcpd-oslo'. To be used in graphite paths.",
        type=str,
        required=True,
    )
    protocol_choices = ("text",) + tuple(str(p) for p in PICKLE_PROTOCOL)
    parser.add_argument(
        "-P",
        "--protocol",
        help="Protocol to use to send to graphite server. Default: %(default)s",
        choices=protocol_choices,
        default=str(DEFAULT_PROTOCOL),
        type=str,
    )
    parser.add_argument(
        "-n",
        "--noop",
        action="store_true",
        help="Do not send metrics to graphite, print what would be sent instead",
    )
    args = parser.parse_args()
    try:
        protocol = int(args.protocol)
    except ValueError:
        pass
    else:
        args.protocol = protocol
    if not args.port:
        if isinstance(args.protocol, int):
            args.port = "2004"
        else:
            args.port = "2003"
    return args


# run command and store json output
def exec_dhcpd_pools(args):
    flags = f"-c {args.config_file} {FLAGS}".split()
    cmd = [args.command] + list(flags)
    result = subprocess.run(cmd, capture_output=True)
    if result.returncode:
        sys.exit(result.stderr)
    return json.loads(result.stdout)


# reformat the data
def render(metrics, args):
    if isinstance(args.protocol, int):
        return _render_pickle(metrics, args)
    return _render_text(metrics, args)


def _render_text(metrics, args):
    template = "{metric.path} {metric.value} {metric.timestamp}\n"
    output = []
    for metric in metrics:
        line = template.format(metric=metric)
        output.append(line)
    return "".join(output).encode("ascii")


def _render_pickle(metrics, args):
    output = []
    for metric in metrics:
        output.append((metric.path, (metric.timestamp, metric.value)))
    payload = pickle.dumps(output, protocol=args.protocol)
    header = struct.pack("!L", len(payload))
    message = header + payload
    return message


def _tuplify(jsonblob, args):
    prefix = args.prefix
    timestamp = trunc(time())
    data = jsonblob["subnets"]
    output = list()
    for subnet_stat in data:
        network = subnet_stat["location"]
        first_ip, last_ip = map(str.strip, subnet_stat["range"].split("-"))
        for key, metric in METRIC_MAPPER.items():
            if network == "All networks":
                path = f"{args.prefix}.dhcp.4.{args.server_name}.range.special_groups.standalone.{first_ip}.{last_ip}.{metric}"
            else:
                path = f"{args.prefix}.dhcp.4.{args.server_name}.range.custom_groups.{network}.{first_ip}.{last_ip}.{metric}"
            value = subnet_stat[key]
            output.append(Metric(path, value, timestamp))
    return output


def _escape_metric_name(name):
    """
    Escapes any character of `name` that may not be used in graphite metric
    names.
    """
    legal_metric_characters = string.ascii_letters + string.digits + "-_"
    name = ''.join([c if c in legal_metric_characters else "_" for c in name])
    return name


# send the data
def send_to_graphite(metrics_blob, server, port):
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    try:
        sock.connect((server, port))
    except socket.error as e:
        sys.exit(str(e))
    try:
        sock.sendall(metrics_blob)
    except socket.error as e:
        sys.exit(str(e))
    finally:
        sock.close()


def main():
    args = parse_args()
    jsonblob = exec_dhcpd_pools(args)
    metrics = _tuplify(jsonblob, args)
    output = render(metrics, args)
    if args.noop:
        if args.protocol == "text":
            print(output.decode('ascii'))
        else:
            print(hexlify(output).decode('ascii'))
    else:
        send_to_graphite(output, args.address, args.port)


if __name__ == "__main__":
    main()
