# Uncomment the two lines below this paragraph for NAV to fetch DHCP metrics
# from the Kea DHCPv4 server managed by the Management API served by the Kea
# Control Agent with URI "https://example.org:8080/"


#[https://example.org:8080/]
#dhcp_version=4


# IMPORTANT: If the URI scheme is 'http://', NAV will happily communicate using
# plain HTTP. NAV needs to fetch the configuration file of the Kea DHCP server
# to collect subnet-specific metrics, and this will be sent in plaintext over
# the network if HTTP is used. As the configuration file may contain
# confidential data (such as passwords), it is highly reccomended to use HTTPS
# if connections to the URI might cross an insecure network. Use HTTPS by
# specifying the URI scheme 'https://'.

# Only DHCPv4 servers (dhcp_version=4) are supported. (Kea DHCPv6 servers have a
# different set of available metrics. Support for metrics from Kea DHCPv6 might
# be added in the future.)
