# This file contains the configuration for collection of stats from endpoints
# not necessarily part of the network managed by NAV. A section in this
# configuration that configures one specific endpoint must have a name that
# starts with 'endpoint_':
#
# [endpoint_oslo_dhcp_1] <--- Valid endpoint name
# option1=value1
# option2=value2
#
# [oslo_dhcp_1] <--- Invalid endpoint name
# option1=value1
# option2=value2


# Configuring collection of stats from 'Kea DHCPv4' endpoints
# ===========================================================
#
# Mandatory options
# -----------------
# * The 'type' option, specifying what type of endpoint is being configured. Its
#   value must be set to 'kea-dhcp4'
#
# * The 'url' option, specifying where the endpoint is located. The url's scheme
#   must be 'http' or 'https'. Sensitive data such as possible passwords stored
#   in the Kea DHCPv4 server's configuration is transmitted during
#   correspondence (and also temporarily stored in the memory of the local
#   process), so using 'https' is highly reccomended.
#
# Optional options
# ----------------
# * The 'http_basic_username' and 'http_basic_password' optional options. When
#   both of these options are set, HTTP Basic Authentication will be used in
#   communication with the endpoint.
#
# * The 'client_cert_path' optional option, specifying the path to a client-side
#   certificate.  When this option is set, the certificate will be used to
#   authenticate to the endpoint in TLS connections. If the
#   'client_cert_key_path' option is not set, it is assumed that the certificate
#   also contains the private key.
#
# * The 'client_cert_key_path' optional option. It specifies the path to the
#   private key for the client certificate.
#
# Example configuration
# ---------------------
# [endpoint_example_1]
# type=kea-dhcp4
# url=https://example.org:8080/
# http_basic_username=nav
# http_basic_password=cfcc3475c4de4f0484a4a475ec0a6edd
# client_cert_path=/etc/client.cert
# client_cert_key_path=/etc/client.key
# user_context_pool_name_key=name


[endpoint_demo]
type=kea-dhcp4
url=http://kea:8000/
