# This file contains the configuration for collection of stats from endpoints
# not necessarily part of the network managed by NAV.
#
# Any section whose name starts with the endpoint_ prefix defines a
# new endpoint configuration:
#
# [endpoint_foo] <--- This section configures an endpoint with internal identifier 'foo'
# type=dnsmasq
# url=https://url.to.dnsmasq.server/
#
# [foo] <--- This section does *not* configure an endpoint
# type=dnsmasq
# url=https://url.to.dnsmasq.server/


# The remainder of this commentary documents how to configure the
# various types of endpoints that is supported:


# Configuring collection of stats from 'kea-dhcp4' endpoints
# ==========================================================
#
# Mandatory options
# -----------------
# * The 'type' option, specifying what type of endpoint is being configured. Its
#   value must be set to 'kea-dhcp4'.
#
# * The 'url' option, specifying where the endpoint is located. The url's scheme
#   must be 'http' or 'https'. Sensitive data such as passwords possibly stored
#   in the Kea DHCPv4 server's configuration is transmitted during
#   correspondence (and as a sidenote also temporarily stored in the memory of
#   the local process), so using 'https' is highly recommended.
#
# Optional options
# ----------------
# * The 'http_basic_username' and 'http_basic_password' optional options. When
#   both of these options are set, HTTP Basic Authentication will be used in
#   communication with the endpoint.
#
# * The 'client_cert_path' optional option, specifying the path to a client-side
#   certificate.  When this option is set, the certificate will be used to
#   authenticate to the endpoint in TLS connections. If the
#   'client_cert_key_path' option is not set, it is assumed that the certificate
#   also contains the client private key used to authenticate the client.
#
# * The 'client_cert_key_path' optional option, specifying the path to the
#   client private key to be used alongside the client certificate to
#   authenticate the client.
#
# * The 'user_context_poolname_key' optional option, specifying how NAV finds
#   the human-name of a Kea DHCPv4 address pool. On the server-side each Kea
#   DHCPv4 address pool is configured as a JSON object with a mandatory 'pool'
#   key and an optional 'user-context' key holding an arbitrary JSON
#   object. This NAV-side option specifies which key in this
#   'user-context' object NAV will look up to find the human-name of a Kea
#   DHCPv4 address pool. By default, NAV will look for the 'name'
#   key. Example:
#
#     If 'user_context_poolname_key' has been set to 'custom-poolname' for a Kea
#     DHCPv4 server with the following configuration:
#
#     {
#       "Dhcp4": {
#         "subnet4": [
#           {
#             "subnet":  "172.31.255.0/24",
#             "pools": [
#               {
#                 "pool": "172.31.255.0/25",
#                  "user-context": {
#                    "custom-poolname": "oslo-math-staff"
#                  }
#               }
#             ],
#             "id": 1,
#             "interface": "eth0"
#           }
#         ]
#       }
#     }
#
#     Then NAV will associate with the address pool '172.31.255.0/25' the name
#     'oslo-math-staff'.
#
#
# Example 'kea-dhcp4' configuration
# ---------------------
# [endpoint_example_1]
# type=kea-dhcp4
# url=https://example.org:8080/
# http_basic_username=nav
# http_basic_password=cfcc3475c4de4f0484a4a475ec0a6edd
# client_cert_path=/etc/client.cert
# client_cert_key_path=/etc/client.key
# user_context_poolname_key=name


[endpoint_demo]
type=kea-dhcp4
url=http://kea:8000/
