# This file contains the configuration for collection of stats from endpoints
# not expected to be part of the network managed by NAV.

# Each section configures one endpoint that NAV periodically will fetch metrics
# from and must contain the 'type' option and the 'url' option.  Other options
# are type-dependent.
# Section names (in brackets) that configure an endpoint must start with 'endpoint_'
# and be unique, but can otherwise be arbitrary.

# Mandatory options for all endpoint sections:
# The 'type' option. It specifies what type of endpoint the section
#   configures. Currently, 'kea-dhcp4' is the only valid type.
# The 'url' option. It specifies where the endpoint is located. Use insecure URL
#   schemes such as 'http://' with caution, and do not rely upon being
#   redirected to more secure schemes.

# Additional options for endpoint sections with type 'kea-dhcp4':
# The 'http_basic_username' and 'http_basic_password' optional options. When
#   both of these options are set, HTTP Basic Authentication will be used in
#   communication with the endpoint.
# The 'client_cert_path' optional option. It specifies the path to a client-side
#   certificate.  When this option is set, the certificate will be used to
#   authenticate to the endpoint in TLS connections. If the
#   'client_cert_key_path' option is not set, it is assumed that the certificate
#   also contains the private key.
# The 'client_cert_key_path' optional option. It specifies the path to the
#   private key for the client certificate.


# Example 1 (DHCPv4 metrics from Kea API endpoint):
# -------------------------------------------------
# [endpoint_example_1]
# type=kea-dhcp4
# url=https://example.org:8080/
# http_basic_username=nav
# http_basic_password=cfcc3475c4de4f0484a4a475ec0a6edd
# client_cert_path=/etc/client.cert
# client_cert_key_path=/etc/client.key
# pool_user_context_key=name
# vlan_user_context_key=name
# vlan_user_context_value=vlan%

[endpoint_demo]
type=kea-dhcp4
url=http://kea:8000/
